### Registration
POST http://localhost:8080/api/v1/authorization/registration
Content-Type: application/json

{
  "name": "Vali",
  "surname": "Valiyev",
  "email": "hojiakbarandaqulov5@gmail.com",
  "password": "1234"
}


### Login
POST http://localhost:8080/api/v1/authorization/login
Content-Type: application/json

{
  "phone": "998992431068",
  "password": "1234"
}

### verification
GET http://localhost:8080/api/v1/authorization/verification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjk5NTA3NDgsImlkIjoiZTU4ZWQ3NjMtOTI4Yy00MTU1LWJlZTktZmRiYWFhZGMxNWYzIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6Ijk5ODk5MjQzMTA2OCIsImV4cCI6MTczMDI5NjM0OCwiaXNzIjoiSW50ZXJ2aWV3X3F1ZXN0aW9ucyJ9.dU6-Sh_pdlVnilWescble2vZKhCCT2wK6haSOFBH44Rw1gGhmk4A8-Qnys0EpIDanSMrwhUm2ZedzYwCo6H8RQ

{
  "phone": "998771300918",
  "code": "78041"
}
### resend
GET http://localhost:8080/api/v1/authorization/registration/resend/998771300919
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjk5NTA3NDgsImlkIjoiZTU4ZWQ3NjMtOTI4Yy00MTU1LWJlZTktZmRiYWFhZGMxNWYzIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6Ijk5ODk5MjQzMTA2OCIsImV4cCI6MTczMDI5NjM0OCwiaXNzIjoiSW50ZXJ2aWV3X3F1ZXN0aW9ucyJ9.dU6-Sh_pdlVnilWescble2vZKhCCT2wK6haSOFBH44Rw1gGhmk4A8-Qnys0EpIDanSMrwhUm2ZedzYwCo6H8RQ




### Login
POST http://95.130.227.202:9091/api/v1/authorization/login
Content-Type: application/json

{
  "phone": "998992431068",
  "password": "1234"
}

### verification
GET http://95.130.227.202:9091/api/v1/authorization/verification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjk5NTA3NDgsImlkIjoiZTU4ZWQ3NjMtOTI4Yy00MTU1LWJlZTktZmRiYWFhZGMxNWYzIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6Ijk5ODk5MjQzMTA2OCIsImV4cCI6MTczMDI5NjM0OCwiaXNzIjoiSW50ZXJ2aWV3X3F1ZXN0aW9ucyJ9.dU6-Sh_pdlVnilWescble2vZKhCCT2wK6haSOFBH44Rw1gGhmk4A8-Qnys0EpIDanSMrwhUm2ZedzYwCo6H8RQ

{
  "phone": "998771300919",
  "code": "53304"
}