###profile data update
PUT http://localhost:8080/api/v1/profile/update/12f59a8b-1010-4826-beb3-7e4c29629888
Content-Type: application/json

{
  "name": "Xojiakabr",
  "surname": "Jons",
  "categoryId": 1,
  "photoId": "1"
}


### profile password update
PUT http://localhost:8080/api/v1/profile/update/password/e58ed763-928c-4155-bee9-fdbaaadc15f3
Content-Type: application/json

{
  "newPassword": "123456",
  "repetitionPassword": "123456",
  "confirmation": "123456"
}

### photo create
POST http://localhost:8080/api/v1/profile/create/photo/e58ed763-928c-4155-bee9-fdbaaadc15f3?file=file.png
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.png"

< D:\video\file.png

###
POST http://localhost:8080/api/v1/profile/create/photo/{e58ed763-928c-4155-bee9-fdbaaadc15f3}?
    file={{$random.alphanumeric(8)}}