### Authorization
POST https://notify.eskiz.uz/api/auth/login
Content-Type: application/json

{
  "email": "handaqulov51@gmail.com",
  "password": "TBpAnEfk8CuMPnOZlqxzfXrxJRugKwb9m7vXmfyZ"
}

### Send sms
POST https://notify.eskiz.uz/api/message/sms/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzI3MDkyMjIsImlhdCI6MTczMDExNzIyMiwicm9sZSI6InRlc3QiLCJzaWduIjoiY2M3MzMwOWJiMzcyMTE5MWY3ZDdhNjA1NWQyNjhjNjFlYTUzYjVmNzZlMGMxN2IzMjM2ZjQyM2JkNmQ2NDY5YyIsInN1YiI6Ijc0MDcifQ.yugABt55o8XcANA-GVyiIi01Uce2DFBa93-co5O8nko

{
  "mobile_phone": "+998771300918",
  "message": "Bu Eskiz dan test",
  "from": "4546"
}

### Authorization
POST https://notify.eskiz.uz/api/v1/authorization/login
Content-Type: application/json

{
  "email": "19mrasul@gmail.com",
  "password": "9"
}

### Send sms
POST https://notify.eskiz.uz/api/message/sms/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTkwNzE0MzYsImlhdCI6MTcxNjQ3OTQzNiwicm9sZSI6InVzZXIiLCJzaWduIjoiYWQ3ZmZkZjg1NWE5NmJiYjkxYWNiNGM5Y2VjZDliMWYxMDlmOThkN2QxNDc5NGJhN2M0ZmIwODhmOTBiNTMyNiIsInN1YiI6IjEwMzMifQ.PP19N2-m9sV0IyMQJ8Pb4zEcxIdcYBNs5q9qJSp0jwE

{
  "mobile_phone": "+998771300918",
  "message": "YouGo ilovasiga ro'yxatdan o'tishning tasdiqlash kodi: 12345",
  "from": "4546"
}

###
GET http://95.130.227.202:9091/api/v1/authorization/verification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjk5NjM4MTgsImlkIjoiZTU4ZWQ3NjMtOTI4Yy00MTU1LWJlZTktZmRiYWFhZGMxNWYzIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6Ijk5ODk5MjQzMTA2OCIsImV4cCI6MTczMDMwOTQxOCwiaXNzIjoiSW50ZXJ2aWV3X3F1ZXN0aW9ucyJ9.dU30C89nwup4mEIvEgTxiSpbd1f9FfP8Lv8PS0VMJIQP2MfOVXMiTCIn84qCxYlcR41WuY4hfzIqOIavclP_Zg

{
  "phone": "998771300918",
  "code": "53399"
}